name: Own Pipeline Phonebook Application

on:
    push:
        branches:
            - main
jobs:
    own_pipeline:
            runs-on: ubuntu-latest
            steps:
                - name: Checkout code
                  uses: actions/checkout@v2

                - name: Set up Node.js
                  uses: actions/setup-node@v2
                  with:
                    node-version: '18x'

                - name: Install dependencies
                  run: npm install

                - name: Build the application
                  run: npm run build:webpack

                - name: Deploy to production
                  run: npm run start