GET http://localhost:3001/api/persons
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"Liisa",
    "number" :"39-885545845"
    
}

###

DELETE http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "id":2
}

###

GET https://phonebook-backend-test.fly.dev/api/persons

###

POST https://phonebook-backend-test.fly.dev/api/persons
Content-Type: application/json

{
    "name": "Liisa",
    "number" :"39-8855458425"
    
}

###
DELETE https://phonebook-backend-test.fly.dev/api/persons/2 HTTP/1.1
Content-Type: application/json
 