# fly.toml app configuration file generated for phonebook-backend-mostafa on 2024-03-13T14:59:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-backend-mostafa'
primary_region = 'cdg'

[build]

[env]
  PORT = "3000" # add this

[deploy]
--smoke-checks=false

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
